# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Run test project
      run: dotnet test MatGPT/MatGPTTestProject
    
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: restor
      run: dotnet restore
    - name: build
      run: dotnet build
    - name: pub
      run: dotnet publish -r linux-x64  
    - name: Instal EF tools
      run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef --version 6.0.29
    - name: build bundle
      run: dotnet ef migrations bundle --self-contained -r linux-x64 --project "MatGPT" --startup-project "MatGPT"
      
      
